name: Continuous Integration

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

# ensure that the workflow is only triggered once per PR,  subsequent pushes to the PR will cancel
# and restart the workflow. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Create build directory
          run: mkdir -p build
        - uses: ilammy/msvc-dev-cmd@v1
          if: matrix.os == 'windows-latest'
        - name: Build Linux
          working-directory: build
          run: ../make-lib.sh
          if: matrix.os == 'ubuntu-latest' 
        - name: Build Windows
          working-directory: build
          run: ..\nmake-lib.bat
          if: matrix.os == 'windows-latest'
        - name: Build MacOS
          working-directory: build
          run: ../make-lib.sh
          if: matrix.os == 'macos-latest'